### ISSUE TITLE
VisualEditor windows are cut off

### ISSUE THREAD

**Issue by ghost** [InternationalScratchWiki/ScratchWikiSkin2#123] opened 2023-02-12 11:16 UTC
![image](https://user-images.githubusercontent.com/69243388/218307611-a7c97dd7-b71b-4607-a27f-51577033e2b5.png)
(screenshot taken in an unsaved edit to my sandbox on the English Wiki)
VisualEditor windows are cut off, for example, when pressing the link button when editing. This would make it virtually impossible to add links or some other features when editing with VisualEditor.

**Comment by SausageMcSauce** [comment] 2023-02-19 09:49
![image](https://user-images.githubusercontent.com/69243388/219940561-89f623d3-39de-4e6b-8730-831fa5b84077.png)
This seems to be the cause; the height of these popups is not set by our skin whilst Vector 2022 (added in the 1.39 upgrade) does (although I do not know where it is being set for this element, as it uses inline style)

**Comment by Kenny2github** [comment] 2023-12-22 07:16
Noticed this during the course of another PR. This completely disables VE features using such popups. Elevating priority.

**Comment by jacob-g** [comment] 2024-07-18 00:29
This appears to have been resolved in a more recent release of VisualEditor. Please reopen if this issue recurs.

**Closed by jacob-g** 2024-07-18 00:29 UTC
Labels: bug, prio-medium

**Comment by Kenny2github** [comment] 2024-07-18 00:46
This was actually resolved tangentially in #131 but I forgot to note that here.
