### ISSUE TITLE
Wikitable styling doesn't work in MW 1.39

### ISSUE THREAD

**Issue by jacob-g** [InternationalScratchWiki/ScratchWikiSkin2#116] opened 2022-10-10 16:30 UTC
For this:
```html
<table class="wikitable">
...table contents...
</table>
```

These tables are showing as unstyled in MW 1.39.

**Comment by Kenny2github** [comment] 2022-12-24 19:48
Wikitables [should still be around](https://www.mediawiki.org/wiki/Help:Tables#class=%22wikitable%22) so something else sussy is going on here...

**Comment by Kenny2github** [comment] 2022-12-30 07:00
This is likely a duplicate of #109

**Comment by Kenny2github** [comment] 2022-12-30 07:22
Duplicate of #109

**Closed** 2023-03-07 03:29 UTC
Labels: enhancement, has-patch, prio-high
