### ISSUE TITLE
Error boxes are no longer styled in MW 1.39

### ISSUE THREAD

**Issue by jacob-g** [InternationalScratchWiki/ScratchWikiSkin2#115] opened 2022-10-10 16:29 UTC
The new markup is this:
```html
<div class="mw-message-box-error mw-message-box">...contents of error...</div>
```

They are not showing up styled; we need to add that.

**Comment by Kenny2github** [comment] 2022-12-30 07:00
This is likely a duplicate of #109

**Comment by Kenny2github** [comment] 2022-12-30 07:22
Duplicate of #109

**Closed** 2023-03-07 03:29 UTC
Labels: enhancement, has-patch, prio-high
