### ISSUE TITLE
Awkward line at the bottom of all pages (including special pages) on MW 1.39

### ISSUE THREAD

**Issue by jacob-g** [InternationalScratchWiki/ScratchWikiSkin2#117] opened 2022-10-10 16:34 UTC
![image](https://user-images.githubusercontent.com/1960707/194913705-1d9429cb-56ec-46c7-9d19-3fc60bab8324.png)

**Comment by Kenny2github** [comment] 2022-12-30 07:21
Duplicate of #109

**Closed** 2023-03-07 03:29 UTC
Labels: enhancement, has-patch, prio-high
